// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfidiqskcchpkcyhjjyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmaWRpcXNrY2NocGtjeWhqanl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjU1NDEsImV4cCI6MjA2NzI0MTU0MX0.W_bBsCteUQPXNJdprVPULhp88PtHUm5Lc3lFoHyb1F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});